<!--ZOOMSTOP-->
<div id="sidebar" class="sidebar">

	<!-- The Block With All The Upcoming Dates -->
	<?php include $PARTSDIR . '/dates.php'; ?>

	<!-- The Navigation Menu with all the links
		All of the sidebar's HTML will be generated by this php function.
		The sidebar is generated based on the contents of sidebar.json

		If you're looking to edit/add/delete the sidebar's links, link text,
		link structure, link nesting, then look in /data/sidebar.json

		If you're looking to edit the sidebar's style, then
		obviously you'd look in /css/components/sidebar.css
	
		If you actually need to edit the Sidebar's Inner HTML, which is an
		unlikely possibility, it's in /php/functions.php... but I'd
		rather you just come get me in person and I'll do it.

		Consider, if what you want is achievable by adding a class to the 
		<ul> below and targeting .sidebar > ul.classname. I left the root
		<ul> outside of the function on purpose.

		-->
	<ul class="sidebar-menu">
		<?php echo GetSidebar(); ?>
	</ul>

</div>

<!-- This secret div gives the impression that the sidebar
	extends to the bottom of the page. It just adds a black box
	where the sidebar should be... down below where the sidebar
	no longer reaches.
	Just ignore this. -->
<div class="sidebar_imitator"></div>
<!--ZOOMRESTART-->