pageinfo = [[0,0,0,0,null],
	[1492706580,0,0,12,null],
	[1492706579,0,0,12,null],
	[0,0,9,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[0,0,8,0,null],
	[1492706583,0,0,12,null],
	[1492706581,0,0,12,null],
	[1492706581,0,0,12,null],
	[1492706569,0,8,5,null],
	[1492706574,0,0,12,null],
	[1492706581,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706580,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706577,0,0,12,null],
	[1492706578,0,0,12,null],
	[1492706573,0,0,12,null],
	[1492706574,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706582,0,0,12,null],
	[1492706574,0,0,12,null],
	[1492706580,0,0,12,null],
	[1492706574,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706580,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706582,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706577,0,0,12,null],
	[1492706574,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706578,0,0,12,null],
	[1492706577,0,0,12,null],
	[1492706583,0,0,12,null],
	[1492706583,0,0,12,null],
	[1492706569,0,8,5,null],
	[1492706579,0,0,12,null],
	[1492706568,0,8,5,null],
	[1492706576,0,0,12,null],
	[1492706582,0,0,12,null],
	[1492706578,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706581,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706577,0,0,12,null],
	[1492706576,0,0,12,null],
	[1492706575,0,0,12,null],
	[1492706574,0,0,12,null],
	[1492706578,0,0,12,null],
	[1492706570,0,8,5,null],
	[1492706582,0,0,12,null],
	[1492706582,0,0,12,null],
	[0,0,8,0,null],
	[1492706576,0,0,12,null],
	[1492706582,0,0,12,null],
	[0,0,8,0,null],
	[1492706580,0,0,12,null]];
pagedata = [ ["http://edocs.healthlinx.com/nateneap/","The Index Page","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/","healthlinx_logo.gif","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 3.4 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/","winchester.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 35 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/index.php","The Index Page","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/NEAP_Introduction_Purpose/intro-purpose.php","NEAP: Intro &#38; Purpose","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","Outcome Team","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/cms-data.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/evaluating-hospitals.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/penalties-bonuses.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/level-outcomes.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/patient-surveys.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/timely-effective-care.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-hypothesis-cms.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-emergency.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-surgical.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-other.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/cms-incentives-faq.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-executive.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-director.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-view.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-quarterly.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-performance.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-magnet-requirements.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/healthlinx-methodology.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/internal-vertical.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/high-risk.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/moderate-risk.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/low-risk.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/no-risk.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-financial-impact.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-action-plan.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-high-performance.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-under-performance.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/internal-horizontal.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/leadership-vacancy-hypothesis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/stretch-coverage-hypothesis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/horizontal-intersection-hypothesis-ulso.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/underperformance-hypothesis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/other-hypothesis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/available-leadership.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-surgical.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-or-nurse-manager.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-ed-dir.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-behavorial-nm.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-ed-nurse-manager.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-critical-care-dir.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Available_Leadership_to_Improve_Outcomes/hih-home-health-dir.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-financial-impact.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-action-plan.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-high-performance.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-under-performance.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/External_Vertical_Analysis/external-vertical-analysis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/pursuit-excellence.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/External_Horizontal_Analysis/external-horizontal-analysis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/magnet-threshold.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/nursing-plan.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/strategic-plan.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/blank-item-1.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Pursuit_of_Excellence/nursing-excellence-scale.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Priorities/priorities.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Priorities/vertical-priorities.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Priorities/horizontal-priorities.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/project-plans-timelines.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/project-analysis.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/soe-delivery-schedule.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/best-practice-timeline-1.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/best-practice-timeline-2.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Investment/investment.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/NEAP_On_Site_Presentation/neap-onsite-presentation.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/NEAP_On_Site_Presentation/report-agenda.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Comprehensive_Status_Reports/comprehensive_status_report.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/NEAP_On_Site_Presentation/future-report-1.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Comprehensive_Status_Reports/future-report-1.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Comprehensive_Status_Reports/future-report-2.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/ULSO_Quarterly_Updates/quarterly_updates.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/ULSO_Quarterly_Updates/q2-report.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/ULSO_Quarterly_Updates/q1-report.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/ULSO_Quarterly_Updates/q3-report.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/ULSO_Quarterly_Updates/q4-report.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Additional_Documents/additional_documents.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/E_Docs_Demo/edocs-demo.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/","vertical-arrow.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 8.4 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/","horizontal-vertical-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 13 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/NEAP_Introduction_Purpose/intro-purpose.php","intro_diagram.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 69 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/attachments/Winchester%20Medical%20Center%20NEAP%20K%20092915.pdf","Winchester Medical?Center NEAP K092915.pdf","",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","CindyHenry.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 341 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","icon_phone.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 289 bytes FileModifyDate: 2017:04:...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","marilyn.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 98 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","icon_email.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 288 bytes FileModifyDate: 2017:04:...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","jeff.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 68 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","jeanine.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 94 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","tammy.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 44 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","valerie.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 78 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","abdou.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 97 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","ethan.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 82 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","icon_info.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 355 bytes FileModifyDate: 2017:04:...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","magnet.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 22 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","cindy.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 515 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/evaluating-hospitals.php","evaluating-hospitals.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 39 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/penalties-bonuses.php","current-summary.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 32 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/penalties-bonuses.php","history-details.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 60 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/patient-surveys.php","green-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 6.1 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/patient-surveys.php","patient-survey-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 42 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/timely-effective-care.php","red-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 6.9 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Outcome_Team/outcome-team.php","nathan.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 94 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-emergency.php","timely-effective-care.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 39 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-emergency.php","cms-incentives-ed.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 23 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-emergency.php","risks-by-department.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 51 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/timely-effective-care.php","timely-efficient-care.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 283 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/CMS_Organizational_Level_View/Horizontal_Intersection_Hypothesis_in_CMS/horizontal-intersection-surgical.php","timely-effective-care-surgical.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 44 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso.php","ulso.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 66 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Unit_Level_Summary_of_Outcomes_ULSO/ulso-performance.php","ulso-raw-view.jpg","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 61 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/attachments/ULSO_Winchester.pdf","ULSO_Winchester.pdf","Winchester Medical Center CEO: Mark H. Merrill CNO: Anne Whiteside NEAP Presentation Date: December 15, 2015 = Underperformance (less than the com...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-financial-impact.php","vertical-financial-impact-chart-2.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 218 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/high-risk.php","mypdf.pdf","Assessment Results Hospital &#38; Nursing Division Organizational Charts Risk: Low Risk Theme: Leadership: (OO4) MagnetÂ&#174; requires the submission of a...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-high-performance.php","leader2_vertical.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 24 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-action-plan.php","PSDleader.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 15 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-financial-impact.php","vertical-financial-impact-chart-1-updated.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 253 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Vertical_Analysis/vertical-under-performance.php","leader3_vertical-under.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 53 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/leadership-vacancy-hypothesis.php","leadership-vacancy-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 271 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-high-performance.php","leader2_horizontal.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 23 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/stretch-coverage-hypothesis.php","stretch-coverage-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 224 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/horizontal-under-performance.php","leader3_horizontal-under.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 76 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/External_Vertical_Analysis/external-vertical-analysis.php","external-vertical-analysis-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 38 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/External_Horizontal_Analysis/external-horizontal-analysis.php","external-horizontal-analysis-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 28 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Internal_Horizontal_Analysis/Horizontal_Intersection_Hypothesis_in_ULSO/underperformance-hypothesis.php","underperformance-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 239 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/attachments/WMCAnnOpPlan091615-Q2Update.pdf","WMCAnnOpPlan091615-Q2Update.pdf","Mission: Serving our community by improving health. Vision: One System, One Purpose - Leading with Innovative Healthcare *Estimate is based on cur...",""],
["http://edocs.healthlinx.com/nateneap/pages/Priorities/priorities.php","priorities-chart.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 41 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/project-analysis.php","overhead.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 104 kB FileModifyDate: 2017:04:20 ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/healthLinx-capacity.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/Project_Plan_Timelines/project-analysis.php","Phase1.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 96 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/Investment/investment.php","padlock_closed.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 11 kB FileModifyDate: 2017:04:20 1...",""],
["http://edocs.healthlinx.com/nateneap/pages/About_HealthLinx/about-healthlinx.php","NEAP","The primary purpose of the Nursing Excellence Assessment and Plan is to identify existing Vertical and Horizontal barriers and/or potential risks ...",""],
["http://edocs.healthlinx.com/nateneap/pages/E_Docs_Demo/edocs-demo.php","edocs-arrow.png","ExifToolVersion: 9.09 FileName: zoom_plugin.in Directory: L:/clienthtml/E-NEAP/NATE_NEAP/pages/Search FileSize: 424 kB FileModifyDate: 2017:04:20 ...",""]];
